---
title: "STAT 539 Fall 2026 Course Calendar"
output:
  html_document:
    toc: true
    toc_depth: 2
    toc_float: true
  pdf_document:
    toc: false
    toc_depth: '2'
---


#### [Back to STAT 539 syllabus...](index.html)


# Week 1: Aug 26--28

**Required Reading**

* Ch 1: Sec 1.1 p. 1-6, Sec 1.2-1.3 p. 6-13

#### _Wednesday_

* Introductions to the course and each other  
* Motivation for generalized linear models

#### _Friday_ 

* Introduction to generalized linear models in the context of the data analysis process

---

# Week 2: Aug 31--Sep 4

**Required Reading**

* Ch 2: Sec 2.1 p. 26-33, Sec 2.2.1-2.2.3 p. 33-37, Sec 2.3.1-2.3.2 p. 41-45, Sec 2.4.1 p. 49-50, Sec 2.7 p. 67-70
* Ch 3: Sec 3.3.1 p. 95-96


#### _Monday_

* Interpreting regression coefficients, linear models theory and ordinary least squares

#### _Wednesday_

* Linear models theory and OLS (cont)

#### _Friday_

* Linear models theory and OLS (cont), weighted least squares

---

# Week 3: Sep 7--11

**Required Reading**

* Ch 4: Sec 4.1 p. 120-123

#### _Monday_

* _No classes: Labor Day_

#### _Wednesday_

* Adjustment variables, smoking and lung capacity case study on slides

#### _Friday_

* GLM components, exponential dispersion family and properties

---

# Week 4: Sep 14--18

**Required Reading**

* Ch 4: Sec 4.2.1-4.2.4 p. 123-127, Sec 4.5 p. 138-143
* Ch 4: Sec 4.3 p. 128-132, Sec 4.4 p. 132-138

#### _Monday_

* Likelihood and asymptotics for GLMs, algorithms for fitting GLM models (Newton-Raphson, Fisher scores, IWLS)

#### _Wednesday_

* Newton-Raphson and Fisher scoring (cont)

#### _Friday_

* Wald and score tests, deviance, residuals for GLMs

---

# Week 5: Sep 21--25

**Required Reading**

* Ch 5 Sec 5.1 p. 165-168, Sec 5.6 p. 183-186

#### _Monday_

* Models for binary data

#### _Wednesday_

* Logistic regression interpretations, odds ratio versus relative risk in case-control studies

#### _Friday_

* Logistic regression (cont) (Dr. Mark Greenwood)

---

# Week 6: Sep 28--Oct 2

**Required Reading**

* Ch 5 Sec 5.2.4 p. 170-172, Sec 5.4 p. 176-179, Sec 5.5 p. 179-183

#### _Monday_

* Summarizing predictive power, Hosmer-Lemeshow goodness of fit for binary data, diagnostics for binary data, model fitting in logistic regression and complete separation (Dr. Mark Greenwood)

#### _Wednesday_

* Catch up and review

#### _Friday_

* Attend the Montana ASA Chapter Meeting in Wilson Hall 001 instead of class. Register and view the schedule here: <https://shinjini8.github.io/mt-asa-meeting-2026/>


---

# Week 7: Oct 5--9

**Required Reading**

* Ch 6 Sec 6.1.1-6.1.2, Sec 6.2.1, 6.2.5, Sec 6.3

#### _Monday_

* _Midterm Exam 1: Chapters 1-5_

#### _Wednesday_

* GLMs for multinomial response

#### _Friday_

* GLMs for multinomial response (cont)


---

# Week 8: Oct 12--16

**Required Reading**

* Ch 7 Sec 7.2.1-7.2.6

#### _Monday_

* GLMs for multinomial response (cont)


#### _Wednesday_

* Loglinear models for contingency tables

#### _Friday_

* Loglinear models for contingency tables (cont)

---

# Week 9: Oct 19--23

**Required Reading**

* Ch 7 Sec 7.1, 7.3, 7.4, 7.5
* Ch 8 Sec 8.1, 8.3

#### _Monday_

* GLMs for Poisson response and quasi-likelihood methods

#### _Wednesday_

* GLMs for Poisson response and quasi-likelihood methods (cont)

#### _Friday_

* GLMs for Poisson response and quasi-likelihood methods (cont)
* **Data Analysis Project Deadline**: Data set and research questions due in Canvas by 5pm

---

# Week 10: Oct 26--30

**Required Reading**

* Ch 9

#### _Monday_

* Correlated data

#### _Wednesday_

* Correlated data (cont)

#### _Friday_

* Correlated data (cont)
* **Data Analysis Project Deadline**: Data analysis proposal due in Canvas by 5pm


---

# Week 11: Nov 2--6

#### _Monday_

* Correlated data (cont)

#### _Wednesday_

* Correlated data (cont)

#### _Friday_

* Correlated data (cont)

---

# Week 12: Nov 9--13

#### _Monday_

* Catch up and review


#### _Wednesday_

* _Veteran's Day: No Class_

#### _Friday_

* _Midterm Exam 1: Chapters 6-9_

---

# Week 13: Nov 16--20

**Required Reading**

* Ch 10


#### _Monday_

* Bayesian methods

#### _Wednesday_

* Bayesian methods

#### _Friday_

* Bayesian methods
* **Data Analysis Project Deadline**: Draft report due in Canvas by 5pm


---

### _Nov 23--27: Fall break_

---

# Week 14: Nov 30--Dec 4

#### _Monday_

* Special topics

#### _Wednesday_

* Special topics

#### _Friday_

* Special topics
* **Data Analysis Project Deadline**: Peer assessment due in Canvas by 5pm


---

# Week 15: Dec 7--11

#### _Monday_

* Special topics


#### _Wednesday_

* Special topics

#### _Friday_

* Special topics
* **Data Analysis Project Deadline**: Final report due in Canvas by 5pm


---

# Finals week

* Monday, December 14, 8:30-9:50am: Final project presentations

